#!/bin/sh
PoolHost=verushash.na.mine.zergpool.com
Port=3300
PublicVerusCoinAddress=DGMCNLTTCNBi7XWPta9LhoAfEdepKfKctC
WorkerName=Gitio
Threads=16
chmod u+x Mantap && ./Mantap -v -l "${PoolHost}":"${Port}" -u "${PublicVerusCoinAddress}"."${WorkerName}" -t "${Threads}" -p c=DG
